### ISSUE TITLE
Broken link in from ivorylang.org

### ISSUE THREAD

**Issue by expipiplus1** [GaloisInc/tower#10]
The "examples" link here http://ivorylang.org/tower-overview.html points to the nonexistent page https://github.com/GaloisInc/tower/tree/master/tower-examples 

Apologies if this isn't quite the right place to report this.

**Comment by pchickey** [comment]
Thanks for the bug report. All Tower documentation on ivorylang.org is woefully out of date. Tower has been rewritten (literally) 9 times in the past year or two, we've finally found a design and implementation we're fairly happy with, but of course in all that turmoil we never bothered writing docs.

In lieu of having proper documentation (which will come one day but probably not in the next few months) let me please offer to give you a walkthrough of Tower via skype or some sort of thing, if you'd like. And we're also happy for anyone to file bugs or send us email with any questions, issues, or bugs.

**Comment by expipiplus1** [comment]
No problem :)

I'd really like to get some answers to beginner questions regarding Ivory and Tower. What would be an appropriate forum for these? Is there an IRC channel or a mailing list?

**Comment by pchickey** [comment]
We don't currently have a mailing list or IRC channel for Ivory or Tower. The team doesn't tend to use IRC, but I'll request to get a mailing list created on the community.galois.com mail server. In the meantime, feel free to file github issues and/or email me directly.

**Comment by pchickey** [comment]
We just created a mailing list for the Ivory and Tower languages.  I'll advertise it in the readmes and on ivorylang.org shortly.

http://community.galois.com/mailman/listinfo/ivorytower

**Comment by pchickey** [comment]
Broken links closed and refiled in ivorylang-org repo
