### ISSUE TITLE
Writing a new backend for Tower

### ISSUE THREAD

**Issue by pjones** [GaloisInc/tower#18]
I'm at the very beginning of a new embedded project and would like to use Ivory and Tower.  For various reasons, the RTOS that I'm going to be using is [Apache Mynewt](http://mynewt.apache.org/) on the [nRF52](https://www.nordicsemi.com/Products/nRF52-Series-SoC) MCU.

My reason for creating this issue is to get some feedback on the perceived risks of using Tower since the documentation is very sparse, it's not on Hackage, and it's not clear if Galois or any other projects are using/maintaining it.

Issue #2 mentions an "OS backend implementation guide", but I don't believe that exists.  One of my major concerns is that the time it will take me to write a Mynewt backend for Tower will cause too much of a delay for the actual project I'm working on.

For anyone who has written a Tower backend, I'm curious how much time it took.  I'm proficient in C and Haskell, though I do need to brush up on extensions such as `DataKinds`.

Any suggestions or feedback would be greatly appreciated.  Thank you.

**Comment by leepike** [comment]
Advantages:
+ The front-end is stable and has been used in a large project (SMACCMPilot), so it is well-tested and there are a lot of examples.
+ We already target the Cortex M4F, so you may be able to reuse some of the BSP.

Disadvantages:
- It will be moderately supported at this point. That is, we intend to support it, by bug fixes, feature requests may take a few weeks (at least) depending on other job constraints.
- It is heavily dependent on Ivory, so you are committing to Ivory, too, if you use Tower.
- Enforces a particular "Hoare Monitor" like approach, which may not be appropriate (e.g., if you ever needed multicore support).
- The backend interface is... complicated. Only core developers have written backends. That said, I'm guessing it'd be a one month endeavor, including time to learn Tower and do debugging.

**Comment by pjones** [comment]
Since Mynewt already handles the HAL and BSP, I wonder if it makes more sense to use Ivory to write a thin binding to Mynewt instead of using Tower.  Any thoughts?

**Comment by leepike** [comment]
That would work. You won't get the guarantees of safe concurrency that Tower provides, but you can always go back later and write the Tower bindings that target your Ivory bindings.

**Comment by pjones** [comment]
Are there any papers or documents that discuss the safe concurrency that Tower provides?

**Comment by leepike** [comment]
This is probably the best that exists: https://www.cs.indiana.edu/~lepike/pub_pages/acsd17.html

**Comment by pjones** [comment]
Thank you for all the input.  I appreciate it.
