### ISSUE TITLE
Feature request: task initialization time code insertion

### ISSUE THREAD

**Issue by jtdaugherty** [GaloisInc/tower#5]
It would be very useful to have a way to generate code to run at task initialization time *in task context*.  For example, some ports of FreeRTOS may provide an FPU and some tasks may need to declare a desire to use it before executing any floating point instructions.  The way this is done is detailed at

http://www.freertos.org/Using-FreeRTOS-on-Cortex-A-Embedded-Processors.html#floating-point

and I'd like to be able to do something like
```
task_stuff :: Task p ()
task_stuff = do
  taskRequiresFPU
```
or, more generally,
```
task_stuff :: Task p ()
task_stuff = do
  taskStartup $ do
    call_ proc_taskRequiresFPU ...
```

**Comment by pchickey** [comment]
this is taken care of / obsoleted by tower9
