### ISSUE TITLE
Stable unique names

### ISSUE THREAD

**Issue by pchickey** [GaloisInc/tower#8]
ping @leepike - you're going to need `Unique` names in the Tower AST to be stable for AADL output to be useful for more than just code generation.

In this case, stable means a string name for a given monitor, handler, callback, etc. should not change from build to build, with arbitrary modifications to the Tower program specified, unless the user changes the string name of the component or parent component, or provides string names that are ambiguous.

One major change required is that channels will need to be given stable names by the user. So, we'll have to make a breaking API change to Tower to give the `channel` constructor a mandatory string as a parameter.

Once channels have user provided string names in the AST, we will make the following changes:
change `Unique` type to be a sum type of `Unambiguous String | Ambiguous String Int`
the Base monad's `StateT Int ...`, used as a fresh name source, will change to StateT ([String], Int) (WriterT [String] ...) - the fresh name source (integer) will keep a log of all `Unambiguous` names provided in addition to having a source for fresh `Ambiguous`, and write a log of each `Ambiguous` name provided to be given to the user as warnings later.
We'll drop the `fresh :: m Int` API in the BaseUtil class and only expose `freshname :: String -> m Unique`. This should be easy because I believe the only place we use `fresh` directly is when constructing `Chan` in the AST.

**Comment by leepike** [comment]
I think this has mostly be fixed by @jameysharp as of 2b801bb221e069343ac42d15d93ed9568f4bf854. Names are stable if unique. Emitter and callback names are still generated but less likely to collide. Channels are unnamed. But I think this is sufficient for the AADL backend for now.

Feel free to close if it works for you.

**Comment by pchickey** [comment]
Jamey's improvements take care of pretty much everything. I really appreciate that generated code is much easier to read :)
